---
apiVersion: v1
kind: Service
metadata:
  name: service-api
spec:
  selector:
    app: service-api
  ports:
    - port: 8080
      name: 'application'

---
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: service-api
  labels:
    imageTag: '1.0.5'
spec:
  revisionHistoryLimit: 15
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: service-api
    spec:
      containers:
      - name: service-api
        image: gcr.io/twitch-223000/service/api:1.0.5
        env:
          - name: PORT
            value: '8080'
          - name: ENVIRONMENT
            value: 'prod'
          - name: LOG_LEVEL
            value: 'info'
          - name: SCHEDULE_ENABLE
            value: 'true'
          - name: SCHEDULE_GAMES_CRON
            value: '*/15 * * * *'
        ports:
          - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 4
        resources:
          limits:
            memory: 1500Mi
          requests:
            memory: 1500Mi
