version: 2

# default node docker image
default_image: &default_image
  docker:
    - image: node:11.1.0

# working directory to use in all jobs
working_directory: &working_directory
  working_directory: ~/repo

# get files from cache
attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/repo

# archive workspace
persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: ~/repo
    paths: ./**

jobs:
  install:
    <<: *working_directory
    <<: *default_image
    steps:
      - checkout
      - restore_cache: # Download and cache dependencies
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - <<: *persist_to_workspace

  test:
    <<: *working_directory
    <<: *default_image
    steps:
      - <<: *attach_workspace
      - run:
          name: Run tests
          command: npm test

  eslint:
    <<: *working_directory
    <<: *default_image
    steps:
      - <<: *attach_workspace
      - run:
          name: Run eslint
          command: npm run eslint


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install:
          context: twitch-envs
      - test:
          context: twitch-envs
          requires:
            - install
      - eslint:
          context: twitch-envs
          requires:
            - install
